# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
      {id: 11, size: 0.150, name: charge_dock_tag},
      # {id: 242, size: 0.0696, name: blissey_tag},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
#     {
#       name: 'target',
#       layout:
#         [
#           {id: 242, size: 0.04, x: -0.0275, y:  0.02875, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 113, size: 0.04, x:  0.0275, y:  0.02875, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 137, size: 0.04, x: -0.0275, y: -0.02875, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#           {id: 440, size: 0.04, x:  0.0275, y: -0.02875, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
#         ]
#     }
  ]
