joystick:
  package: "db_debug_joystick"
  path: "db_debug_joystick.launch"
  topics:
    /joy: None
  on_start: true
move_base:
  package: "db_move_base"
  path: "db_move_base.launch"
  on_start: false
  topics:
    /move_base: None
yolo:
  package: "db_yolo"
  path: "db_yolo.launch"
  on_start: true
