# initial_range: [1.0, 1.0, 1.0]
initial_range: [0.25, 0.25, 0.25]
input_std: [0.005, 0.005, 0.005, 0.005]
meas_std_val: 0.05
num_particles: 50

match_cov: 0.1
match_threshold: 0.9
new_filter_threshold: 0.9
max_num_filters_per_label: 3
