scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.185
    upper_threshold: .inf
- name: camera_obstruction
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 2.4
    upper_angle: 2.9
- name: shield_left
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: 1.36
    upper_angle: 1.78
- name: shield_rear
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -0.21
    upper_angle: 0.21
- name: shield_right
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.78
    upper_angle: -1.36
