global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 0.5
resolution: 0.05
rolling_window: false

footprint_padding: 0.0

inflation:
    enabled: true
    cost_scaling_factor: 3.0
    inflation_radius: 0.5

plugins:
    - {name: static,                    type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,            type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
