# Robot Configuration Parameters
acc_lim_x: 5.0
acc_lim_theta:  5.0

max_vel_x: 1.0  # max speed 4.48 m/s
min_vel_x: 0.2

# for recovery behaviors
max_vel_theta: 2.0  # 61.4
min_vel_theta: 2.0  # -61.4
min_in_place_vel_theta: 2.0

holonomic_robot: false
escape_vel: -1.0

# Goal Tolerance Parameters
yaw_goal_tolerance: 0.075
xy_goal_tolerance: 0.05
latch_xy_goal_tolerance: false

# Forward Simulation Parameters
sim_time: 0.5
sim_granularity: 0.025
angular_sim_granularity: 0.025
vx_samples: 5
vy_samples: 5
vtheta_samples: 20
controller_frequency: 10.0

# Trajectory scoring parameters
meter_scoring: true  # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
occdist_scale:  0.1  # The weighting for how much the controller should attempt to avoid obstacles. default 0.01
path_distance_bias: 1.0  # The weighting for how much the controller should stay close to the path it was given . default 0.6
goal_distance_bias: 0.75  # The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

heading_lookahead: 0.1  # How far to look ahead in meters when scoring different in-place-rotation trajectories
heading_scoring: true  # Whether to score based on the robot's heading to the path or its distance from the path. default false
heading_scoring_timestep: 0.8   # How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
dwa: true  # Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
simple_attractor: false
publish_cost_grid_pc: true

# Oscillation Prevention Parameters
oscillation_reset_dist: 0.25  # How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
escape_reset_dist: 0.1
escape_reset_theta: 0.1
