brightness: 0
contrast: 50
exposure: 166
gain: 256
gamma: 300
hue: 0
saturation: 64
sharpness: 50
frames_queue_size: 16
white_balance: 4600.0

backlight_compensation: false
enable_auto_exposure: true
enable_auto_white_balance: true
auto_exposure_priority: false
global_time_enabled: true
