# Publish scans from best pose at a max of 10 Hz
odom_model_type: omni-corrected
transform_tolerance: 0.2
gui_publish_rate: 1.0
min_particles: 25
max_particles: 700
kld_err: 0.05  # 0.01
kld_z: 0.99  # 0.99
selective_resampling: true  # false

# translation std dev, m
odom_alpha1: 0.05  # 0.2
odom_alpha2: 0.05  # 0.2
odom_alpha3: 0.05  # 0.2
odom_alpha4: 0.05  # 0.2
odom_alpha5: 0.05  # 0.2


laser_model_type: likelihood_field
laser_z_hit: 0.95  # 0.95
laser_z_rand: 0.05  # 0.05
laser_likelihood_max_dist: 4.0

# laser_model_type: beam
# laser_z_hit: 0.8  # 0.95
# laser_z_rand: 0.05  # 0.05
# laser_z_short: 0.1  # 0.1
# laser_z_max: 0.05  # 0.05

laser_sigma_hit: 0.2  # 0.2
laser_lambda_short: 0.1  # 0.1

laser_min_range: 0.25
laser_max_range: 12.0
laser_max_beams: 360


update_min_d: 0.1
update_min_a: 0.05
odom_frame_id: odom
resample_interval: 3
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1