# RTAB-Map's parameters: do "rosrun rtabmap rtabmap (double-dash)params" to see the list of available parameters.

RGBD/ProximityBySpace: true   # Detection over locations (in Working Memory) near in space.
Mem/IncrementalMemory: true
Mem/InitWMWithAllNodes: false
