int8 PICKUP = 1
int8 DELIVER = 2
int8 PARK = 3
int8 DOCK = 4
int8 action

int8 NAMED_GOAL = 1
int8 POSE_GOAL = 2
int8 type
string name
geometry_msgs/PoseStamped pose_stamped
float32 object_grab_cmd
float32 force_threshold
float32 object_z_offset
---
bool success
---
int8 sequence_index
