global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 0.5
resolution: 0.05
static_map: true
rolling_window: false
cost_scaling_factor: 5.0
infration_radius: 0.1
# width: 5.0
# height: 5.0
