global_frame: map
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 0.5
resolution: 0.05
# static_map: true
rolling_window: false
cost_scaling_factor: 3.0
# width: 5.0
# height: 5.0

footprint_padding: 0.02

inflation:
    enabled: true
    cost_scaling_factor: 30.0
    inflation_radius: 0.4

plugins:
    - {name: static,                    type: "costmap_2d::StaticLayer"}
    # - {name: obstacle_layer,            type: "costmap_2d::VoxelLayer"}
    - {name: obstacle_layer,            type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
