### Common costmap parameters ###
robot_radius: 0.17
# obstacle_range: 1.0
# raytrace_range: 2.0
observation_sources: point_cloud_sensor
point_cloud_sensor:
    sensor_frame: camera_link
    data_type: PointCloud2
    topic: /camera/depth/color/points
    marking: true
    clearing: true

transform_tolerance: 0.5  # 0.2
