### Common costmap parameters ###
# robot_radius: 0.17
footprint: [[-0.1556, -0.12], [-0.1556, 0.12], [0.1894, 0.12], [0.1894, -0.12]]
footprint_padding: 0.01
# obstacle_range: 2.0
# raytrace_range: 4.0
obstacle_layer:
    enabled: true
    max_obstacle_height: 0.35
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    publish_voxel_map: true

    observation_sources: point_cloud_sensor
    point_cloud_sensor:
        sensor_frame: camera_link
        data_type: PointCloud2
        topic: /camera/depth_registered/points
        marking: true
        clearing: true

        obstacle_range: 2.0
        raytrace_range: 4.0
        max_obstacle_height: 0.35
        min_obstacle_height: 0.05
        inflation_radius: 0.01
        track_unknown_space: false
        combination_method: 1

# obstacle_layer:
#     enabled: true
#
#     observation_sources: point_cloud_laser_sensor
#     point_cloud_laser_sensor:
#         sensor_frame: camera_link
#         data_type: LaserScan
#         topic: /camera/scan
#         marking: true
#         clearing: false
#
#         obstacle_range: 4.0
#         raytrace_range: 5.0
#         max_obstacle_height: 0.35
#         min_obstacle_height: -0.35
#         inflation_radius: 0.1
#         track_unknown_space: true
#         combination_method: 1

transform_tolerance: 0.5  # 0.2
