### Common costmap parameters ###
robot_radius: 0.144
# obstacle_range: 1.0
# raytrace_range: 2.0
observation_sources: laser_scan
laser_scan:
    sensor_frame: laser
    data_type: LaserScan
    topic: /rplidar/scan
    marking: true
    clearing: true

transform_tolerance: 0.5  # 0.2
