### Common costmap parameters ###
# robot_radius: 0.17
footprint: [[-0.1556, -0.12], [-0.1556, 0.12], [0.1894, 0.12], [0.1894, -0.12]]
footprint_padding: 0.01
# obstacle_range: 2.0
# raytrace_range: 4.0
obstacle_layer:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    publish_voxel_map: true

    observation_sources: point_cloud_sensor bump_sensor laser_sensor
    # observation_sources: point_cloud_laser_sensor bump_sensor laser_sensor
    point_cloud_sensor:
        sensor_frame: camera_link
        data_type: PointCloud2
        topic: /camera/depth_registered/points
        marking: true
        clearing: true

        obstacle_range: 2.0
        raytrace_range: 4.0
        max_obstacle_height: 0.35
        min_obstacle_height: 0.1
        inflation_radius: 0.01
        track_unknown_space: true
        combination_method: 1
    # point_cloud_laser_sensor:
    #     sensor_frame: camera_link
    #     data_type: LaserScan
    #     topic: /camera/scan
    #     marking: true
    #     clearing: true
    #     obstacle_range: 2.0
    #     raytrace_range: 4.0
    #     max_obstacle_height: 0.5
    #     min_obstacle_height: 0.05
    #     inflation_radius: 0.01
    #     track_unknown_space: true
    #     combination_method: 1

    bump_sensor:
        sensor_frame: base_link
        data_type: LaserScan
        topic: /dodobot/bumper_occupancy
        marking: true
        inflation_radius: 0.01
    
    laser_sensor:
        sensor_frame: laser
        data_type: LaserScan
        topic: /scan_filtered
        marking: true
        clearing: true
        inflation_radius: 0.005

transform_tolerance: 0.5  # 0.2
