### Common costmap parameters ###
robot_radius: 0.17
obstacle_range: 4.0
raytrace_range: 5.0
obstacle_layer:
    enabled: true
    # origin_z: 0.0
    # z_resolution: 0.4
    # z_voxels: 1

    observation_sources: point_cloud_sensor
    point_cloud_sensor:
        sensor_frame: camera_link
        data_type: PointCloud2
        topic: /camera/depth_registered/points
        marking: true
        clearing: true

        obstacle_range: 4.0
        raytrace_range: 5.0
        max_obstacle_height: 0.35
        min_obstacle_height: -0.1
        inflation_radius: 0.1
        track_unknown_space: true
        combination_method: 1

transform_tolerance: 0.5  # 0.2
