git clone https://github.com/robopeak/rplidar_ros.git
git clone https://github.com/UbiquityRobotics/raspicam_node.git
git clone https://github.com/wjwwood/serial.git
git clone https://github.com/ros-planning/navigation.git
git clone https://github.com/ros-planning/navigation_experimental.git
git clone https://github.com/ros-planning/navigation_msgs.git
git clone https://github.com/ros-drivers/joystick_drivers.git
git clone https://github.com/ros/geometry2.git
git clone https://github.com/ros-perception/image_common.git
git clone https://github.com/ros-perception/image_transport_plugins.git
git clone https://github.com/ros-perception/vision_opencv.git
git clone https://github.com/ros-teleop/teleop_tools.git
git clone https://github.com/ros-perception/laser_geometry.git
git clone https://github.com/ros-teleop/twist_mux_msgs.git
git clone https://github.com/ros-teleop/twist_mux.git
git clone https://github.com/appliedAI-Initiative/orb_slam_2_ros.git
